// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Context;

#nullable disable

namespace burguermania_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241204223700_AddProductsTable")]
    partial class AddProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Vegan",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true"
                        },
                        new
                        {
                            Id = 2,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            FullDescription = "Uma refeição leve e deliciosa, ideal para quem busca vitalidade e bem-estar. Preparado com hambúrguer grelhado de peito de frango, temperado com ervas finas e cúrcuma, servido em pão integral artesanal. Acompanhado de folhas frescas de rúcula, espinafre e brotos de alfafa, além de rodelas crocantes de pepino, fatias de cenoura e uma pasta de iogurte grego com hortelã. Finalizado com azeite extravirgem e sementes de chia, proporcionando uma refeição balanceada, repleta de sabores e ingredientes naturais.",
                            Name = "X-Fitness",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true"
                        },
                        new
                        {
                            Id = 3,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            FullDescription = "Um sanduíche delicioso e cheio de sabor para quem aprecia uma refeição marcante. Feito com um hambúrguer de 200g de carne bovina Angus, envolto em uma camada crocante de bacon e coberto por uma generosa porção de queijo cheddar derretido. Servido em um pão brioche macio, o sanduíche é recheado com cebolas crocantes, fatias de tomate, alface americana, molho especial de maionese com alho e um toque de ketchup e mostarda. Para dar o toque final, uma camada de pulled pork desfiado e uma pitada de páprica picante, proporcionando uma explosão de sabores a cada mordida.",
                            Name = "X-Infarto",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true"
                        },
                        new
                        {
                            Id = 4,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            FullDescription = "Uma verdadeira obra-prima culinária, desenvolvida para os amantes da boa comida. O hambúrguer, feito com carne Angus macia, é acompanhado por queijo brie derretido e cogumelos trufados, intensificando a sofisticação do prato. Servido em um pão brioche artesanal, é complementado por rúcula fresca e uma maionese artesanal com leve toque cítrico. Cada mordida oferece uma experiência única, equilibrando ingredientes de alta qualidade e texturas incríveis, tornando o X-Gourmet uma opção memorável.",
                            Name = "X-Gourmet",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true"
                        },
                        new
                        {
                            Id = 5,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            FullDescription = "Uma verdadeira homenagem aos clássicos da culinária. O Cheeseburger Tradicional, com hambúrguer grelhado na medida exata, vem acompanhado de queijo cheddar derretido, alface crocante e tomate fresco, tudo em um pão macio. Para quem adora bacon, o X-Bacon traz a crocância perfeita junto ao molho barbecue. O X-Egg, por sua vez, se destaca com o sabor único do ovo frito e gema cremosa. Simples e saborosos, esses hambúrgueres proporcionam prazer e satisfação em cada mordida.",
                            Name = "X-Clássicos",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 1,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Alface-Premium",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 28.989999999999998
                        },
                        new
                        {
                            Id = 2,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 1,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Tomate",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 38.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 1,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Frutas",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 4,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 1,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Salada",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 5,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 2,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Fitness-Grelhado",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 28.989999999999998
                        },
                        new
                        {
                            Id = 6,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 2,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Proteína",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 38.990000000000002
                        },
                        new
                        {
                            Id = 7,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 2,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Low-Carb",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 8,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 2,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Light",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 9,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 3,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Mega-Bacon",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 28.989999999999998
                        },
                        new
                        {
                            Id = 10,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 3,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Parada-Cardíaca",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 38.990000000000002
                        },
                        new
                        {
                            Id = 11,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 3,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Queijo-Extra",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 12,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 3,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Triplo",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 13,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 4,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Trufado-Supreme",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 58.990000000000002
                        },
                        new
                        {
                            Id = 14,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 4,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Blue-Cheese-Delight",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 68.989999999999995
                        },
                        new
                        {
                            Id = 15,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 4,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Mediterrâneo",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 78.989999999999995
                        },
                        new
                        {
                            Id = 16,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 4,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Deluxe",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 17,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 5,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Cheeseburger-Tradicional",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 28.989999999999998
                        },
                        new
                        {
                            Id = 18,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 5,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Bacon",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 38.990000000000002
                        },
                        new
                        {
                            Id = 19,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 5,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Egg",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        },
                        new
                        {
                            Id = 20,
                            BaseDescription = "Pão, hambúrguer, alface, tomate, queijo e maionese.",
                            CategoryId = 5,
                            FullDescription = "Um hambúrguer vegano recheado de sabor, feito com grão-de-bico e quinoa, temperado com especiarias defumadas, cebola caramelizada e alho, criando uma textura irresistível e cheia de sabor. Servido em um pão macio, é acompanhado de fatias frescas de tomate, alface crocante, picles, abacate cremoso e uma camada generosa de maionese de ervas vegana. Finalizado com molho barbecue agridoce e uma pitada de pimenta-do-reino recém-moída, oferecendo uma explosão de sabores e texturas em cada mordida.",
                            Name = "X-Tudo",
                            PathImage = "https://github.com/ojuaragabriel/Projeto-Angular-JS-BurguerMania/blob/main/src/app/assets/images/image4.png?raw=true",
                            Price = 48.990000000000002
                        });
                });

            modelBuilder.Entity("WebAPI.Models.ProductOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");
                });

            modelBuilder.Entity("WebAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Em Processamento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finalizado"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Tesste@testemail.com",
                            Name = "Testando testanto",
                            Password = "HelloWorld1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "flamengo@flamail.com",
                            Name = "anonimo nonimo",
                            Password = "Helloworld2"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.UserOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrders");
                });

            modelBuilder.Entity("WebAPI.Models.Order", b =>
                {
                    b.HasOne("WebAPI.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WebAPI.Models.Product", b =>
                {
                    b.HasOne("WebAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAPI.Models.ProductOrder", b =>
                {
                    b.HasOne("WebAPI.Models.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPI.Models.UserOrder", b =>
                {
                    b.HasOne("WebAPI.Models.Order", "Order")
                        .WithMany("UserOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("UserOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebAPI.Models.Order", b =>
                {
                    b.Navigation("ProductOrders");

                    b.Navigation("UserOrders");
                });

            modelBuilder.Entity("WebAPI.Models.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("WebAPI.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Navigation("UserOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
